import Interest from "../models/Interest.js";
import Progress from "../models/Progress.js";
import Recommendation from "../models/Recommendation.js";
import { generateAiInsights } from "../services/aiService.js";
import {
  buildRuleBasedRecommendations,
  collectLearningSummary
} from "../services/recommendationService.js";

export const getRecommendations = async (req, res, next) => {
  try {
    const interests = await Interest.find({ user: req.user._id }).sort({ priority: -1 });
    const progressEntries = await Progress.find({ user: req.user._id });
    const ruleBased = await buildRuleBasedRecommendations(req.user._id, interests, progressEntries);
    const summary = await collectLearningSummary(req.user._id);
    const aiInsights = await generateAiInsights({
      user: req.user,
      interests,
      summary,
      recommendations: ruleBased
    });

    await Recommendation.deleteMany({ user: req.user._id, source: "ai" });
    await Recommendation.create({
      user: req.user._id,
      source: "ai",
      title: aiInsights.result.headline,
      description: aiInsights.result.insights.join(" "),
      category: interests[0]?.name || "General",
      reason: `Generated by ${aiInsights.provider} insights`,
      priority: 5,
      actionUrl: ""
    });

    const allRecommendations = await Recommendation.find({ user: req.user._id }).sort({
      priority: -1,
      createdAt: -1
    });

    res.json({
      success: true,
      data: {
        summary,
        recommendations: allRecommendations,
        ai: aiInsights
      }
    });
  } catch (error) {
    next(error);
  }
};
