import Recommendation from "../models/Recommendation.js";
import { generateAiInsights } from "../services/aiService.js";
import {
  buildRuleBasedRecommendations,
  collectLearningSummary
} from "../services/recommendationService.js";

export const getRecommendations = async (req, res, next) => {
  try {
    const ruleBased = await buildRuleBasedRecommendations(req.user._id);
    const summary = await collectLearningSummary(req.user._id);
    const aiInsights = await generateAiInsights({
      user: req.user,
      summary,
      recommendations: ruleBased
    });

    await Recommendation.deleteMany({ user: req.user._id, source: "ai" });

    if (aiInsights.result?.headline) {
      await Recommendation.create({
        user: req.user._id,
        domain: ruleBased[0]?.domain?._id || ruleBased[0]?.domain,
        topic: ruleBased[0]?.topic?._id || ruleBased[0]?.topic,
        source: "ai",
        title: aiInsights.result.headline,
        description: aiInsights.result.strategy || aiInsights.result.insights?.join(" ") || "Personalized AI learning guidance.",
        category: ruleBased[0]?.category || summary.progressByDomain?.[0]?.domain || "General",
        reason: `Generated by ${aiInsights.provider} using progress, weak areas, and rule-based candidates.`,
        priority: 5,
        nextTopic: {
          title: aiInsights.result.nextTopic || ruleBased[0]?.nextTopic?.title || "",
          difficulty: ruleBased[0]?.nextTopic?.difficulty || "Adaptive",
          subdomain: ruleBased[0]?.nextTopic?.subdomain || "AI suggested"
        },
        actionUrl: ruleBased[0]?.actionUrl || "",
        aiPayload: aiInsights.result
      });
    }

    const allRecommendations = await Recommendation.find({ user: req.user._id })
      .populate("domain")
      .populate("topic")
      .sort({ priority: -1, createdAt: -1 });

    res.json({
      success: true,
      data: {
        summary,
        recommendations: allRecommendations,
        ai: aiInsights
      }
    });
  } catch (error) {
    next(error);
  }
};
